name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: install deps
        run: |
          npm --prefix ./.github/actions/joke-action install ./.github/actions/joke-action
          npm --prefix ./.github/actions/issue-maker install ./.github/actions/issue-maker

      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: jokes


      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}
